swagger: '2.0'
info:
    title: gcTSDB REST API
    description: An abstraction layer to use Cassandra as a Time Series Database
    version: 0.0.1
basePath: "/v1"
produces:
    - application/json
paths:
    /channels:
        get:
            summary: Get a list of channels
            description: |
                Use this endpoint to get a list of channels.
            tags:
                - Channels
            parameters:
                - name: name
                  in: query
                  description: name's prefix you want to filter
                  required: false
                  type: string
            responses:
                '200':
                    description: list of channels
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/Channel'
                default:
                    description: Unexpected Error
                    schema:
                        $ref: '#/definitions/Error'

        post:
            summary: Create new channel
            description: |
                Use this endpoint to create a new channel
            tags:
                - Channels
            parameters:
                - name: createChannelRequest
                  in: body
                  description: CreateChannelRequest
                  required: true
                  schema:
                      $ref: '#/definitions/Channel'
            responses:
                '201':
                    description: channel created
                    schema:
                        $ref: '#/definitions/Created'
                default:
                    description: Unexpected error
                    schema:
                        $ref: '#/definitions/Error'


definitions:
    Error:
        type: object
        properties:
            errorCode:
                type: string
                description: error code
            errorMessage:
                type: string
                description: en_US error message
    Created:
        type: object
        properties:
            id:
                type: string
                description: ID of created object
            link:
                type: string
                description: URL to retrieve created object

    Channel:
        type: object
        properties:
            name:
                type: string
                description: channel name
                example: car.wheel.frontleft.temperature
            datatype:
                type: string
                description: |
                    channel's data type.
                    valid options: int32, int64, float32, float64, decimal, string
                example: float32
            bucketSize:
                type: number
                format: integer
                description: bucket size in nanoseconds
                example: 3600000000000
